#!/usr/bin/env bash
set -euo pipefail

GRADLE_VERSION="9.8.0"
GRADLE_DIST_SHA256="bafd5ce9cfaea0fbccfdc8439a1ac42fbd4cd9c89dc9a988228d8a2639a58e6c"
GRADLE_WRAPPER_JAR_SHA256="238e777fcddd7e34f9708186085def2abd6e08e658505b38718d79d74c21abd5"

if command -v nix >/dev/null 2>&1; then
    nix flake lock
fi

if ! command -v gradle >/dev/null 2>&1; then
    cat >&2 <<'MSG'
Gradle is not on PATH.
Run this script inside the Nix development shell, for example:

  nix develop --command ./bootstrap-m0.sh

or enable direnv first:

  direnv allow
  ./bootstrap-m0.sh
MSG
    exit 1
fi

echo "Generating Gradle ${GRADLE_VERSION} wrapper..."
gradle wrapper \
    --gradle-version "${GRADLE_VERSION}" \
    --distribution-type bin \
    --gradle-distribution-sha256-sum "${GRADLE_DIST_SHA256}"

# Run the target wrapper once so the scripts and wrapper JAR are generated by
# the exact Gradle version pinned above rather than whichever bootstrap Gradle
# happened to be supplied by nixpkgs.
./gradlew wrapper \
    --gradle-version "${GRADLE_VERSION}" \
    --distribution-type bin \
    --gradle-distribution-sha256-sum "${GRADLE_DIST_SHA256}"

if command -v sha256sum >/dev/null 2>&1; then
    actual_wrapper_sha="$(sha256sum gradle/wrapper/gradle-wrapper.jar | awk '{print $1}')"
elif command -v shasum >/dev/null 2>&1; then
    actual_wrapper_sha="$(shasum -a 256 gradle/wrapper/gradle-wrapper.jar | awk '{print $1}')"
else
    echo "Cannot verify gradle-wrapper.jar: no SHA-256 utility found." >&2
    exit 1
fi

if [[ "${actual_wrapper_sha}" != "${GRADLE_WRAPPER_JAR_SHA256}" ]]; then
    echo "gradle-wrapper.jar checksum mismatch" >&2
    echo "expected: ${GRADLE_WRAPPER_JAR_SHA256}" >&2
    echo "actual:   ${actual_wrapper_sha}" >&2
    exit 1
fi

echo "Writing Gradle dependency locks and SHA-256 verification metadata..."
./gradlew :core:dependencies :storage-nio:dependencies :platform-linux:dependencies --write-locks --write-verification-metadata sha256

echo "Running initial build..."
./gradlew build

cat <<'MSG'

M0 bootstrap complete.

Review and commit the generated reproducibility inputs:
  flake.lock
  gradlew
  gradlew.bat
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  core/gradle.lockfile
  storage-nio/gradle.lockfile
  platform-linux/gradle.lockfile
  gradle/verification-metadata.xml

The verification metadata is bootstrapped from the artifacts downloaded on
this machine. Review it before treating it as a security boundary.
MSG
