package dev.totipo.format;

/** Bootstrap-only outcome. No root, semantic readiness, or historical revocation claim. */
enum PasswordChangeStatus {
    SUCCESS, REPLACEMENT_UNSUPPORTED,
    CURRENT_AUTHENTICATION_FAILED, CURRENT_INVALID_BOOTSTRAP, CURRENT_INVALID_PASSWORD_INPUT,
    CURRENT_CANONICAL_ABSENT, BOOTSTRAP_STORAGE_UNAVAILABLE, ESTABLISHED_BINDING_MISMATCH,
    INVALID_NEW_PASSWORD_INPUT, CRYPTO_CONSTRUCTION_FAILED, REWRAP_INCOMPLETE,
    LOCAL_BINDING_ABSENT, LOCAL_BINDING_CORRUPT,
    LOCAL_STORAGE_UNAVAILABLE
}
