"""Check the unsigned Maven boundary using only Python's standard library."""
from pathlib import Path
import hashlib
import json
import struct
import xml.etree.ElementTree as ET
import zipfile

ROOT = Path(__file__).resolve().parents[1]
VERSION = (ROOT / "VERSION").read_text().removesuffix("\n")
REPO = ROOT / "build/repository"
URL = "https://github.com/totipo-dev/totipo-java"
NS = {"m": "http://maven.apache.org/POM/4.0.0"}
HASHES = {"md5", "sha1", "sha256", "sha512"}


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def entries(path):
    with zipfile.ZipFile(path) as jar:
        files = {n: jar.read(n) for n in jar.namelist() if not n.endswith("/")}
        require(len(files) == len([n for n in jar.namelist() if not n.endswith("/")]), f"Duplicate entry: {path}")
        return files


hashes = {}
expected_repo = set()
for module, title in [("core", "Totipo Java Core"), ("storage-nio", "Totipo Java NIO Storage")]:
    artifact = f"totipo-{module}"
    directory = REPO / "dev/totipo" / artifact / VERSION
    prefix = f"{artifact}-{VERSION}"
    expected = {f"{prefix}{suffix}" for suffix in [".jar", "-sources.jar", "-javadoc.jar", ".pom", ".module"]}
    actual = {p.name for p in directory.iterdir()}
    require(expected <= actual, f"Missing files: {expected - actual}")
    for name in actual - expected:
        base, algorithm = name.rsplit(".", 1)
        require(base in expected and algorithm in HASHES, f"Unexpected publication file: {name}")
        require((directory / name).read_text().strip() == hashlib.new(algorithm, (directory / base).read_bytes()).hexdigest(), f"Bad checksum: {name}")
    expected_repo.update(p.relative_to(REPO) for p in directory.iterdir())
    # Maven repository index is generated by Gradle; timestamps here are not release artifact bytes.
    index = directory.parent / "maven-metadata.xml"
    index_xml = ET.parse(index).getroot()
    require(index_xml.findtext("groupId") == "dev.totipo" and index_xml.findtext("artifactId") == artifact, "Bad repository index")
    require([v.text for v in index_xml.findall("versioning/versions/version")] == [VERSION], "Unexpected staged versions")
    expected_repo.add(index.relative_to(REPO))
    for algorithm in HASHES:
        checksum = index.with_name(index.name + "." + algorithm)
        if checksum.exists():
            require(checksum.read_text().strip() == hashlib.new(algorithm, index.read_bytes()).hexdigest(), "Bad index checksum")
            expected_repo.add(checksum.relative_to(REPO))
    pom = ET.parse(directory / f"{prefix}.pom").getroot()
    def value(path):
        return pom.findtext("/".join("m:" + part for part in path.split("/")), namespaces=NS)
    for key, expected_value in {"groupId": "dev.totipo", "artifactId": artifact, "version": VERSION,
                                "name": title, "url": URL, "licenses/license/name": "Apache License 2.0",
                                "licenses/license/url": "https://www.apache.org/licenses/LICENSE-2.0.txt",
                                "developers/developer/id": "ingon", "developers/developer/name": "Nikolay Petrov",
                                "developers/developer/url": "https://github.com/ingon/", "scm/url": URL,
                                "scm/connection": f"scm:git:{URL}.git",
                                "scm/developerConnection": "scm:git:ssh://git@github.com/totipo-dev/totipo-java.git"}.items():
        require(value(key) == expected_value, f"{artifact}: wrong {key}: {value(key)}")
    require(bool(value("description")), "Missing description")
    dependencies = [[dep.findtext("m:" + k, namespaces=NS) for k in ["groupId", "artifactId", "version", "scope"]]
                    for dep in pom.findall("m:dependencies/m:dependency", NS)]
    target = ["org.bouncycastle", "bcprov-jdk18on", "1.86", "runtime"] if module == "core" else ["dev.totipo", "totipo-core", VERSION, "compile"]
    require(dependencies == [target], f"Wrong POM dependencies: {dependencies}")
    require(not pom.findall(".//m:optional", NS) and not pom.findall(".//m:classifier", NS), "Unexpected optional/classifier dependency")
    metadata = json.loads((directory / f"{prefix}.module").read_text())
    require(metadata["component"] == {"group": "dev.totipo", "module": artifact, "version": VERSION, "attributes": {"org.gradle.status": "release"}}, "Wrong module component")
    require(metadata["formatVersion"] == "1.1", "Unexpected metadata format")
    require(":core" not in json.dumps(metadata) and ":storage-nio" not in json.dumps(metadata), "Project path leakage")
    variants = metadata["variants"]
    require({v["name"] for v in variants} == {"apiElements", "runtimeElements", "sourcesElements", "javadocElements"}, "Unexpected variants")
    for variant in variants:
        require(not variant.get("capabilities") and not variant.get("dependencyConstraints") and not variant.get("available-at"), "Unexpected variant metadata")
        wanted = []
        if variant["name"] == "runtimeElements" or (module == "storage-nio" and variant["name"] == "apiElements"):
            wanted = [{"group": target[0], "module": target[1], "version": {"requires": target[2]}}]
        require(variant.get("dependencies", []) == wanted, f"Wrong module dependencies: {variant}")
        suffix = {"apiElements": ".jar", "runtimeElements": ".jar", "sourcesElements": "-sources.jar", "javadocElements": "-javadoc.jar"}[variant["name"]]
        require([f["name"] for f in variant["files"]] == [prefix + suffix], "Wrong variant files")
        if variant["name"] in {"apiElements", "runtimeElements"}:
            require(variant["attributes"]["org.gradle.jvm.version"] == 17, "Wrong published Java target")
        for file in variant["files"]:
            require(file["url"] == file["name"] and file["name"] in expected, "Wrong module artifact")
            data = (directory / file["name"]).read_bytes()
            require(file["size"] == len(data), "Wrong module size")
            for algorithm in HASHES & file.keys():
                require(file[algorithm] == hashlib.new(algorithm, data).hexdigest(), "Wrong module checksum")
    binary = entries(directory / f"{prefix}.jar")
    classes_root = ROOT / module / "build/classes/java/main"
    production = {str(p.relative_to(classes_root)): p.read_bytes() for p in classes_root.rglob("*.class")}
    require(production, "No production classes")
    require(set(binary) == set(production) | {"META-INF/MANIFEST.MF"}, "Non-production binary contents")
    for name, data in production.items():
        require(binary[name] == data, f"Wrong class bytes: {name}")
        require(struct.unpack(">IHH", data[:8]) == (0xCAFEBABE, 0, 61), f"Not Java 17: {name}")
    sources = entries(directory / f"{prefix}-sources.jar")
    source_root = ROOT / module / "src/main/java"
    production_sources = {str(p.relative_to(source_root)): p.read_bytes() for p in source_root.rglob("*.java")}
    require(set(sources) == set(production_sources) | {"META-INF/MANIFEST.MF"}, "Non-production source contents")
    require(all(sources[n] == data for n, data in production_sources.items()), "Wrong source bytes")
    docs = entries(directory / f"{prefix}-javadoc.jar")
    docs_root = ROOT / module / "build/docs/javadoc"
    generated_docs = {str(p.relative_to(docs_root)): p.read_bytes() for p in docs_root.rglob("*") if p.is_file()}
    require("index.html" in docs and set(docs) == set(generated_docs) | {"META-INF/MANIFEST.MF"}, "Wrong Javadoc contents")
    require(all(docs[n] == data for n, data in generated_docs.items()), "Wrong Javadoc bytes")
    for name in sorted(expected):
        path = directory / name
        hashes[str(path.relative_to(REPO))] = hashlib.sha256(path.read_bytes()).hexdigest()
    print(f"{artifact}: POM {dependencies}; metadata, contents, Java 17 and unsigned file inventory OK")
require({p.relative_to(REPO) for p in REPO.rglob("*") if p.is_file()} == expected_repo, "Unexpected repository artifacts")
(ROOT / "build/publication-sha256.json").write_text(json.dumps(hashes, indent=2, sort_keys=True) + "\n")
print(json.dumps(hashes, indent=2, sort_keys=True))

# Staged bytes are outputs of this checkout, so their expected hashes are generated
# after structural/content validation, not pinned to one JDK vendor's compilation.
# External BC bytes remain pinned in the committed template; no trust exceptions.
smoke = ROOT / "publishing/consumer-smoke"
template = (smoke / "verification-metadata-template.xml").read_text()
components = []
for artifact in ["totipo-core", "totipo-storage-nio"]:
    artifacts = []
    for suffix in [".jar", ".pom", ".module"]:
        name = f"{artifact}-{VERSION}{suffix}"
        digest = hashes[f"dev/totipo/{artifact}/{VERSION}/{name}"]
        artifacts.append(f'         <artifact name="{name}"><sha256 value="{digest}" origin="Verified local staging output"/></artifact>')
    components.append(f'      <component group="dev.totipo" name="{artifact}" version="{VERSION}">\n' + "\n".join(artifacts) + '\n      </component>')
(smoke / "gradle").mkdir(exist_ok=True)
(smoke / "gradle/verification-metadata.xml").write_text(template.replace("   </components>", "\n".join(components) + "\n   </components>"))
